create type public.app_role as enum ('viewer','bending_manager','windows_manager','admin');
create type public.event_type as enum ('component_production','window_production','window_dispatch','inventory_adjustment','inventory_count','event_reversal');
create table public.profiles (id uuid primary key references auth.users on delete cascade, email text not null, display_name text, role app_role not null default 'viewer');
create table public.products (id text primary key, name text not null, target_quantity numeric not null default 40, active boolean not null default true);
create table public.components (id text primary key, name text not null, responsibility text not null check(responsibility in ('bending','assembly','warehouse','other')), active boolean not null default true, work_time_seconds integer, display_order integer not null);
create table public.bom (product_id text references products on delete cascade, component_id text references components, quantity numeric not null check(quantity>0), primary key(product_id,component_id));
create table public.inventory_baselines (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), created_by uuid references profiles, note text not null);
create table public.inventory_baseline_items (baseline_id uuid references inventory_baselines on delete cascade, item_type text check(item_type in ('product','component')), item_id text not null, quantity numeric not null, primary key(baseline_id,item_type,item_id));
create table public.inventory_events (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), created_by uuid references profiles, user_role app_role not null, event_type event_type not null, item_type text check(item_type in ('product','component')), item_id text, quantity numeric, note text, related_event_id uuid references inventory_events, bom_snapshot jsonb, negative_stock_approved boolean default false);
create table public.inventory_event_lines (id bigint generated always as identity primary key, event_id uuid not null references inventory_events, item_type text check(item_type in ('product','component')), item_id text not null, quantity numeric not null);
create index on public.inventory_events(created_at desc); create index on public.inventory_event_lines(item_type,item_id);
create or replace function public.report_window_production(p_product_id text,p_quantity numeric,p_note text default '',p_negative_approved boolean default false) returns uuid language plpgsql security invoker as $$ declare v_id uuid:=gen_random_uuid(); begin if p_quantity<=0 then raise exception 'quantity must be positive'; end if; insert into inventory_events(id,created_by,user_role,event_type,item_type,item_id,quantity,note,bom_snapshot,negative_stock_approved) values(v_id,auth.uid(),(select role from profiles where id=auth.uid()),'window_production','product',p_product_id,p_quantity,p_note,(select jsonb_agg(b) from bom b where product_id=p_product_id),p_negative_approved); insert into inventory_event_lines(event_id,item_type,item_id,quantity) values(v_id,'product',p_product_id,p_quantity); insert into inventory_event_lines(event_id,item_type,item_id,quantity) select v_id,'component',component_id,-quantity*p_quantity from bom where product_id=p_product_id; return v_id; end $$;
-- Implement analogous RPCs for component production, dispatch, adjustment and inventory count before enabling production mode.
